### ISSUE TITLE
Dimensions

### ISSUE THREAD

**Issue by TachibanaYoshino** [liuzhi19121999/AnimeGANv3Pytorch#1]
https://github.com/liuzhi19121999/AnimeGANv3Pytorch/blob/59a010ee92aad754e1e32e06f7374df0a0d8e47c/DTGAN.py#L23

The height and width dimensions in pytorch should be 2 and 3.

**Comment by liuzhi19121999** [comment]
I've made corrections for the issue you found, and I’m looking forward to your team's next version of AnimeGAN. 👍👍🌹🌹👏👏
